nod-ai/sdxl-scripts

tuning/autotune.py
tuning/tune.py

autotune.py:
1. Changed the third input for shell command ./compile_unet_candidate.sh from device_id to input_mlir_file in compile_unet_candidates()
2. Fixed the bug where the global constant DEFAULT_DEVICE_LIST wasn't applied to default value of --device 
3. Add logging.debug(<function_name>) to each function
tune.py:
1. Replaced the remaining print() with tune_logger.info()

Fix tuning script bugs

---

tuning/autotune.py
tuning/benchmark_dispatch.sh
tuning/tune.py

autotune.py: 
1. Added dataclass `CandidateTracker`
2. Added progress bar for all candidates processing functions, excluding `generate_candidates()`
tune.py:
1. Fixed incompatibilities with `autotune.sh` (directory existed issue)
benchmark_dispatch.sh:
1. Edited a dir name (`compiled/failed` -> `compiled/benchmark_failed`)

Add candidate tracker and progress bar to autotune.py

---

int8-model/compile-punet-base.sh
int8-model/compile-punet.sh

- Disable const eval
- Rename scripts to compile-punet*
- Dump scheduling statistics as well

Compile punet to `executable-sources`

---

tuning/compile_unet_candidate.sh
tuning/unet.sh

compile-unet-base.sh was moved under `fp16-model` dir in new commits, update it to the correct path in `unet.sh` and `compile_unet_candidate.sh`.

Update compile-unet-base.sh path in tuner

---

tuning/tune.py

`output` is a string, so we can't use the path join operator `/` without constructing a path first.

[tuner] Fix pickle path type

---

tuning/autotune.py
tuning/test_tune.py
tuning/tune.py

Refactor the input module parser to track the original shapes and element types. Simplify the configuration enumeration logic to use a single loop shared between all dispatch types.
This is to enable tuning for dispatches with new data types (int8, fp8) without duplicating the existing logic.
Also add a verbose flag to `tune.py`.

[tuner] Track input problem size and element types

---

tuning/autotune.py
tuning/test_tune.py
tuning/tune.py

* Add conv-specific constraints that considers problem size in relation to tiled dims.
* Relax some of the existing constraints when in doubt.
I tested this on 3 sample dispatch and the compiling rate is:
* conv: 72%
* mmt: 40%
* batch mmt: 34%

[tuner] Add constraints for conv. Relax general constraints.

---

tuning/autotune.py

1. `run_command()` missing return `result` after merged #65 
2. Solved the legacy issue where the actual best candidates are not listed properly in `best.log` in `benchmark_compiled_candidates()`.
> print([i[0] for i in best_results])
> best_results = sorted(best_results, key=lambda x: x[0])
> print([i[0] for i in best_results])
> /*
> ['715.0', '921.0', '727.0', '728.0', '925.0', '727.0', '925.0', '735.0', '806.0', '1063.0', '1062.0', '1064.0', '1078.0', '798.0']
> ['1062.0', '1063.0', '1064.0', '1078.0', '715.0', '727.0', '727.0', '728.0', '735.0', '798.0', '806.0', '921.0', '925.0', '925.0']
> */
- `x[0]` is type `str`, and they are sorted lexicographically, which is why "1062.0" comes before "715.0".
- Convert to `float` will solve the issue

[tuner] Fix missing return bug and incorrect sort order in best.log

---

tuning/autotune.py

- Unet benchmarking orders are sorted by candidate's `first_benchmark_time`, fast dispatches go first in unet benchmarking.
- Changed arguments type in some function from `list[candidate_path]` to `list[candidate_index] `

[tuner] Add unet benchmarking prioritization

---

tuning/autotune.py

- Add new attributes in `CandidateTracker` to track more info related to benchmarking parallelization
- Add class `TaskTuple` and `TaskResult` to better organize the result returned by subprocessing
- Add class `BenchmarkOutput` to organize output of `benchmark_unet_candidate.sh`
- Improve `run_command_wrapper()` to increase flexibility and adaptability (i.e. able to cover the feature of `worker_run_command_with_device_id()`)
- Enable multiprocessing in `benchmark_unet()`
- Display benchmark time diff in `unet_results.log`
> e.g.
> Benchmarking: unet_baseline.vmfb on device 6
> BM_run_forward/process_time/real_time_median        554 ms          555 ms            5 items_per_second=1.8046/s
> 
> Benchmarking: unet_candidate_22.vmfb on device 6
> BM_run_forward/process_time/real_time_median …

[tuner] Add unet benchmarking parallelization

---

gpu_ids.py
power_trace.sh

The power trace script needed to be moved out of the fp16 folder. It also needs a couple extra steps done to keep up with some new issues in smutrace.
The gpu_ids.py script is a clumsy way to relate the divergent IDs that GPUs get in various tools. No warranty or guarantee!

Update power trace script and add IDs script

---

tuning/autotune.py
tuning/test_autotune.py

autotune.py:
- Move existing code to function `collision_handler()`
- Add new attr `compiled_vmfb_hash` to `CandidateTracker`
- Add collision detection in `compile_candidates()`
test_autotune.py:
- Add test `test_collision_handler()`

[tuner] Add collision detection for candidate compilation

---

tuning/autotune.py
tuning/test_autotune.py

- Added --dry-run option to allow user running autotune.py without mi300
- Add `generate_dryrun_dispatch_benchmark_results()` and `generate_dryrun_unet_benchmark_results()`
> `benchmark_compiled_candidates()` and `benchmark_unet()` will generate fake results when in dry-run mode

[tuner] Add dry run mode to enable testing without mi300

---

tuning/autotune.py
tuning/test_autotune.py

- if candidate or the baseline doesn't finish, it prints warning to the terminal and store in `unet_result.log`
- candidate unet results will be sorted in ascending benchmark time order
- add new test cases for `parse_grouped_benchmark_results()`

[tuner] Handle incomplete benchmark results

---

tuning/autotune.py
tuning/test_autotune.py
tuning/tune.py

1. Rewrite some expression in `autotune.py` and add `assert` to pass mypy test
2. Use `# type: ignore` to resolve mypy missing-imports errors for now. May change `mypy.ini` in future for such issues.
3. Add new test for `res.get_*()` function of classes `DispatchBenchmarkResult` and `UnetBenchmarkResult`

[tuner] Fix mypy errors. Add new test

---

tuning/autotune.py
tuning/benchmark_dispatch.sh
tuning/benchmark_unet_candidate.sh
tuning/test_autotune.py

The input will be verified against the available devices on the user's machine.
The old implementation of `--devices` was taking in an integer, it will now take in a string representing the device's Path / UUID.
* Adds: `fetch_available_devices() -> list[any]` - Returns the list of all of the devices found by the IREE Runtime module
* Adds: `validate_devices(user_devices) -> None` - Takes in the user input and checks it against the available devices and throws an error if at least one of the user's devices is invalid.
* Modified: `parse_devices(devices_str: str) -> list[str]` - The documentation of the method has been updated and `validate_devices` will be called to validate the user input
* Modified: `parse_arguments()` - The help message has been updated to better represent what the new …

[tuner] Add device validation for user devices

---

tuning/autotune.py
tuning/test_autotune.py

Now there will be 3 logs generated by `autotune.py`
1. `autotune_###.log`: Provides a trace of the script's execution steps.
2. `output.log`: Captures outputs generated during the script run.
3. `result_summary.log`: Summarizes important info and spec contents of top candidates

[tuner] Combine multiple log files

---

tuning/libtuner.py
tuning/punet_autotune.py

[tuner] Remove args.mode

---

int8-model/benchmark-unet.sh
int8-model/compile-punet-base.sh
int8-model/compile-punet.sh
int8-model/specs/attention_and_matmul_spec_punet_mi300_qpx.mlir

Cleanup punet flags and add a placeholder spec for tuning on QPX. Also add an argument to compile-punet.sh for the chip configuration (for selecting the right tuning spec). Current tuning specs have no effect compared against default tile-and-fuse matmuls, so the placeholder spec has no tuning for matmuls yet.

Cleanup punet flags, add placeholder spec for QPX tuning

---

int8-model/specs/attention_and_matmul_spec_punet_mi300_qpx.mlir

Add tuning specs for top 10 matmuls in BS 14 punet. Total tuning improvement from matmul tuning on MI300X QPX mode is now `6.5%`.

[MI300X][QPX] Tune top 10 matmuls for punet batch size 14

---

int8-model/compile-punet-base.sh

Renames `iree-codegen-llvmgpu-test-tile-and-fuse-matmul` to `iree-codegen-llvmgpu-early-tile-and-fuse-matmul` after flag name changed in IREE.

Rename iree-codegen-llvmgpu-test-tile-and-fuse-matmul flag

---

int8-model/compile-punet-base.sh

Adds flag for HZ fusion (off by default due to performance regressions), and removes the transpose convolution filter preprocessing pass due to new numeric regressions. The old pre processing flags (with conv filter transpose) are kept as a comment.

Update punet compilation flags for HZ fusion and transpose convolution

---

int8-model/compile-punet.sh
int8-model/specs/attention_and_matmul_spec_punet_mi300_none.mlir

Adds a placeholder tuning spec with no matmul or convolution tuning. This makes it easier to test without matmul/conv tuning.

Add spec option for no tuning

---

int8-model/specs/attention_and_matmul_spec_punet_mi300_cpx.mlir
int8-model/specs/attention_and_matmul_spec_punet_mi300_qpx.mlir

Add tuning for convs and matmuls in CPX batch size 1 punet, and QPX batch size 14 punet. For QPX batch size 14 punet, the convs are tuned for both the HWCF filter layout and the FHWC filter layout.

Tune MI300X CPX Punet Batch size 1 and MI300X QPX Punet Batch Size 14

---

fp8-model/benchmark-unet.sh
fp8-model/compile-punet.sh
fp8-model/specs/attention_and_matmul_spec_punet_mi325_qpx.mlir

Tunes the top 32 convs/matmuls in punet BS2. The total gain from this tuning is 2.5%.

Tune top 32 BS2 punet dispatches on MI325 QPX

---

fp8-model/specs/attention_and_matmul_spec_vae_mi300_qpx.mlir
int8-model/specs/attention_and_matmul_spec_vae_mi300_qpx.mlir

This new spec file is tuned on the SDXL MLPERF IREE branch and has some slight differences, however I didn't see any actual perf improvement compared to the previous tuning when benchmarking.

Update VAE MI3000-QPX spec file (no perf improvement)
